development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base %>